const countries = ["Bangladesh", "India", "Japan", "Egypt", "Russia"];

const states = {
  Bangladesh: ["Sylhet", "Dhaka", "Barishal", "Rajshahi"],
  India: ["Delhi", "Bangalore", "Chhattisgarh", "Bihar"],
  Japan: ["Hokkaido", "Tohoku", "Chubu", "Kinki"],
};

const districts = {
  Sylhet: ["Habiganj", "Sunamganj", "Moulvibazar"],
  Dhaka: ["Gazipur", "Gopalganj"],
  Barishal: ["Barguna", "Bhola"],
  Rajshahi: ["Natore", "Pabna", "Bogura"],
  Delhi: ["North-East Delhi", "South-West Delhi"],
  Bangalore: ["Kolar", "Chikkaballapura"],
  Chhattisgarh: ["Durg", "Raipur"],
  Bihar: ["Sitamarhi", "Siwan"],
  Hokkaido: ["Hidaka", "Iburi"],
  Tohoku: ["Aomori", "Iwate"],
  Chubu: ["Aichi", "Ishikawa"],
  Kinki: ["Kyoto", "Osaka"],
};

const cities = {
  Habiganj: ["Ajmiriganj", "Bahubal"],
  Sunamganj: ["Bishwamvarpur", "Derai"],
  Moulvibazar: ["Barlekha", "Juri"],
  Gazipur: ["Kapasia", "Tongi"],
  Gopalganj: ["Hathwa"],
  Barguna: ["Amtali", "Betagi"],
  Bhola: ["Daulatkhan"],
  Natore: ["Bagatipara", "Baraigram"],
  Pabna: ["Atgharia", "Bera"],
  Bogura: ["Adamdighi", "Kahaloo"],
  "North-East Delhi": ["Karawal Nagar", "Yamuna"],
  "South-West Delhi": ["Togan Pur", "Binda Pur"],
  Kolar: ["Bangarapet", "Malur"],
  Chikkaballapura: ["Gauribidanur", "Bagepalli"],
  Durg: ["Durg"],
  Raipur: ["Arang", "Abhanpur"],
  Sitamarhi: ["Bairgania", "Bajpatti"],
  Siwan: ["Maharajganj"],
  Hidaka: ["Hidaka"],
  Iburi: ["Iburi"],
  Aomori: ["Aomori"],
  Iwate: ["Iwate"],
  Aichi: ["Aisai", "Anjō"],
  Ishikawa: ["Nonoichi"],
  Kyoto: ["Southern Higashiyama", "Northern Higashiyama"],
  Osaka: ["Minami", "Shinsaibashi"],
};

const towns = {
  Ajmiriganj: ["Badalpur", "Jolsuka"],
  Bahubal: ["Bhadeshwar", "Lamatashi"],
  Bishwamvarpur: ["Dhanpur", "Fatepur"],
  Derai: ["Charnarchar", "Jagdal"],
  Barlekha: ["Borni", "Dasherbazar"],
  Juri: ["Fultola", "Gowalbari"],
  Kapasia: ["Durgapur", "Ghagotia"],
  Tongi: ["Tongi"],
  Hathwa: ["Hathwa"],
  Amtali: ["Arpangasia", "Chawra"],
  Betagi: ["Bibichini", "Buramazumdar"],
  Daulatkhan: ["Charpata", "Hazipur"],
  Bagatipara: ["Dayarampur", "Faguardiar"],
  Baraigram: ["Chandai", "Gopalpur"],
  Atgharia: ["Debottar", "Ekdanta"],
  Bera: ["Dhalar Char", "Jatshakhni"],
  Adamdighi: ["Adamdighi Sadar", "Chapapur"],
  Kahaloo: ["Bir Kedar", "Jamgaon"],
  "Karawal Nagar": ["Karawal Nagar"],
  Yamuna: ["Yamuna"],
  "Togan Pur": ["Togan Pur"],
  "Binda Pur": ["Binda Pur"],
  Bangarapet: ["Bangarapet"],
  Malur: ["Malur"],
  Gauribidanur: ["Gauribidanur"],
  Bagepalli: ["Bagepalli"],
  Maharajganj: ["Maharajganj"],
  Hidaka: ["Hidaka"],
  Iburi: ["Usu", "Shiraoi"],
  Aomori: ["Aomori"],
  Iwate: ["Iwate"],
  Aisai: ["Aisai"],
  Anjō: ["Anjō"],
  Nonoichi: ["Nonoichi"],
  "Southern Higashiyama": ["Southern Higashiyama"],
  "Northern Higashiyama": ["Northern Higashiyama"],
  Minami: ["Minami"],
  Shinsaibashi: ["Shinsaibashi"],
};

const zipCodes = {
  Ajmiriganj: [3360],
  Bahubal: [3310],
  Bishwamvarpur: [3010],
  Derai: [3040],
  Barlekha: [3250],
  Juri: [3251],
  Kapasia: [1730],
  Tongi: [1230, 1710],
  Hathwa: [841436],
  Amtali: [8710],
  Betagi: [8740],
  Daulatkhan: [8310],
  Bagatipara: [6410],
  Baraigram: [6432],
  Atgharia: [6610],
  Bera: [6681, 6683],
  Adamdighi: [5890, 5892],
  Kahaloo: [5870],
  "Karawal Nagar": [110094],
  Yamuna: [135001, 135001, 135001, 135001],
  "Togan Pur": [160014],
  "Binda Pur": [110059],
  Bangarapet: [563114],
  Malur: [563130],
  Gauribidanur: [561208],
  Bagepalli: [561207],
  Durg: [490001, 491223, 491771],
  Arang: [493441],
  Abhanpur: [493661],
  Bairgania: [843313],
  Bajpatti: [843314],
  Maharajganj: [273303],
  Hidaka: ["350-1200"],
  Iburi: ["787-0302"],
  Aomori: ["030-0111"],
  Iwate: ["028-4211"],
  Aisai: [26000],
  Anjo: ["444-1151"],
  Nonoichi: ["921-0000"],
  "Southern Higashiyama": ["504-0861", "731-4226"],
  "Northern Higashiyama": ["045-0002", "068-0820"],
  Minami: ["232-0000"],
  Shinsaibashi: ["542-0085"],
};

// eslint-disable-next-line import/no-anonymous-default-export
export default { countries, states, districts, cities, towns, zipCodes };
